version: "3"
services:
  broker:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-kraft
    container_name: kafka-kraft
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
        KAFKA_NODE_ID: 1 
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT' 
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-kraft:29092,PLAINTEXT_HOST://localhost:9092' 
        KAFKA_JMX_PORT: 9101 
        KAFKA_JMX_HOSTNAME: localhost 
        KAFKA_PROCESS_ROLES: 'broker,controller' 
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-kraft:29093' 
        KAFKA_LISTENERS: 'PLAINTEXT://kafka-kraft:29092,CONTROLLER://kafka-kraft:29093,PLAINTEXT_HOST://0.0.0.0:9092' 
        KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT' 
        KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER' 
        CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka-kraft:29092"
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
